### ISSUE TITLE
Make logo visible

### ISSUE THREAD

**Issue by HassanBahati** [qraft-Inc/Qraft-Store-Innersource-FrontEnd#14]
The logo seems to blend into the background of the navigation bar thereby making it hard to be seen.

## Possible Cause
The logo might not have a color declared thereby inheriting the color of its background

## Possible Fix 
Confirm if the logo actually has a color defined, if not not set a color, 

If that doesn't work, please reach out for a new logo svg that you would replace with the current

You can preview this [here](https://deploy-preview-13--qraftstorealpha.netlify.app/)
![Screenshot from 2022-11-10 11-41-45](https://user-images.githubusercontent.com/65954740/201046011-ff849a38-ab42-4348-836f-06f4aa5307a0.png)

**Comment by amyyalex** [comment]
The logo blends into the background because that is the actual picture color of the logo, as seen in the image link https://res.cloudinary.com/dwa3soopc/image/upload/v1618146785/qraft%20/Artboard 4 copy 7 eyjqs9.png.
Because the logo is a picture, changing the color has no effect on it, and using a filter to change the color doesn't make it look good as it changes the entire logo concept. So I believe the solution is to reach out for a new logo svg and replace with the current

**Comment by amyyalex** [comment]
> The logo blends into the background because that is the actual picture color of the logo, as seen in the image link https://res.cloudinary.com/dwa3soopc/image/upload/v1618146785/qraft%20/Artboard 4 copy 7 eyjqs9.png. Because the logo is a picture, changing the color has no effect on it, and using a filter to change the color doesn't make it look good as it changes the entire logo concept. So I believe the solution is to reach out for a new logo svg and replace with the current

correct link:  https://res.cloudinary.com/dwa3soopc/image/upload/v1618146785/qraft%20/Artboard_4_copy_7_eyjqs9.png

**Comment by amyyalex** [comment]
> The logo blends into the background because that is the actual picture color of the logo, as seen in the image link https://res.cloudinary.com/dwa3soopc/image/upload/v1618146785/qraft%20/Artboard 4 copy 7 eyjqs9.png. Because the logo is a picture, changing the color has no effect on it, and using a filter to change the color doesn't make it look good as it changes the entire logo concept. So I believe the solution is to reach out for a new logo svg and replace with the current

corrrect link: https://res.cloudinary.com/dwa3soopc/image/upload/v1618146785/qraft%20/Artboard_4_copy_7_eyjqs9.png
